server:
  port: 80

mybatis:
    type-aliases-package: com.amvue.amvueserver
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath*:com/amvue/**/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://193.112.75.134:4002/amvue
    username: root
    password: abc123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

